### ISSUE TITLE
#1 - Cadastro e login

### ISSUE THREAD

**Issue by RonaldMacario13** [netrometro/UPE-2022.2-Equipe01#1]
O sistema deve detectar qual é o tipo de usuário que está tentando fazer login e direcioná-lo para a página correta.

**Comment by netrometro** [comment]
Olá Ronald,

A história do usuário pertence ao usuário, lhe entregando valor. Não começa pelo "sistema". O sistema não é um usuário.
Leia o slide referente ao assunto para seguir o modelo proposto.

Para tratar de login e logout utilize a palavra 'autenticação".
